server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          auth-oidc:
            provider: spring
            client-id: auth
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "http://auth-server:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: auth-oidc
          auth-authorization-code:
            provider: spring
            client-id: auth
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "http://auth-server:8080/authorized"
            scope: message.read,message.write
            client-name: auth-authorization-code
          auth-client-credentials:
            provider: spring
            client-id: auth
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: auth-client-credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000

messages:
  base-uri: http://127.0.0.1:8090/messages
